/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents/{agent_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agent Runs
         * @description List agent runs for an agent with pagination.
         */
        get: operations["list_agent_runs_api_agents__agent_id__runs_get"];
        put?: never;
        /**
         * Run Agent
         * @description Run an agent.
         */
        post: operations["run_agent_api_agents__agent_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/runs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Streaming Agent
         * @description Run an agent in priority mode and stream events via Server-Sent Events (SSE).
         */
        post: operations["run_streaming_agent_api_agents__agent_id__runs_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent Run
         * @description Get agent run details.
         */
        get: operations["get_agent_run_api_agents__agent_id__runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Agent Run
         * @description Cancel agent run.
         */
        delete: operations["delete_agent_run_api_agents__agent_id__runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contents/{source_connection_content_version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Content Detail
         * @description Get detailed information about a specific content version.
         */
        get: operations["get_content_detail_api_contents__source_connection_content_version__get"];
        put?: never;
        post?: never;
        /**
         * Delete Content
         * @description Delete a specific content version.
         */
        delete: operations["delete_content_api_contents__source_connection_content_version__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contents/{source_connection_content_version}/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Content Embeddings
         * @description List embeddings for a specific content version.
         */
        get: operations["list_content_embeddings_api_contents__source_connection_content_version__embeddings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description List content sources with pagination.
         */
        get: operations["list_sources_api_sources__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_connection_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a file to a content source
         * @description Upload a file to a content source.
         *
         *     **Maximum file size:** 209715200 bytes.
         *
         *     **Supported MIME types:**
         *     - `application/epub+zip`
         *     - `application/json`
         *     - `application/msword`
         *     - `application/pdf`
         *     - `application/vnd.ms-excel`
         *     - `application/vnd.ms-outlook`
         *     - `application/vnd.ms-powerpoint`
         *     - `application/vnd.openxmlformats-officedocument.presentationml.presentation`
         *     - `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
         *     - `application/vnd.openxmlformats-officedocument.wordprocessingml.document`
         *     - `application/xml`
         *     - `application/zip`
         *     - `audio/flac`
         *     - `audio/mp4`
         *     - `audio/mpeg`
         *     - `audio/ogg`
         *     - `audio/wav`
         *     - `image/bmp`
         *     - `image/gif`
         *     - `image/jpeg`
         *     - `image/png`
         *     - `image/tiff`
         *     - `image/webp`
         *     - `text/csv`
         *     - `text/html`
         *     - `text/markdown`
         *     - `text/plain`
         *     - `text/x-markdown`
         *     - `text/xml`
         *     - `video/mp4`
         *     - `video/quicktime`
         *     - `video/x-msvideo`
         *
         *     Notes:
         *     - If the uploaded file's content type is `application/octet-stream`, the server attempts to infer the type from the file extension.
         */
        post: operations["upload_file_to_source_api_sources__source_connection_id__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentRunAttemptResponse */
        AgentRunAttemptResponse: {
            /**
             * Duration
             * @description Duration of the attempt in seconds.
             */
            duration: number | null;
            /**
             * Ended At
             * @description Timestamp when the attempt ended.
             */
            ended_at: string | null;
            /**
             * Error
             * @description Error message if the attempt failed.
             */
            error: string | null;
            /**
             * Started At
             * @description Timestamp when the attempt started.
             */
            started_at: string | null;
            /** @description Status of the agent run attempt. */
            status: components["schemas"]["PendingProcessingCompletedFailedStatus"];
        };
        /** AgentRunRequest */
        AgentRunRequest: {
            /**
             * Input
             * @description Input to provide to the agent upon running for agents with dynamic triggers.
             */
            input: string | null;
            /**
             * Metadata
             * @description Metadata to make available for string substitution expressions in agent tasks.
             */
            metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /**
             * Priority
             * @description If true, the agent run will be treated as priority execution.
             * @default false
             */
            priority: boolean;
        };
        /** AgentRunResponse */
        AgentRunResponse: {
            /**
             * Attempts
             * @description List of attempts made for this agent run.
             */
            attempts: components["schemas"]["AgentRunAttemptResponse"][];
            /**
             * Credits
             * @description Credits consumed by the agent run, if applicable.
             */
            credits: number | null;
            /**
             * Error Count
             * @description Number of errors encountered during the run.
             */
            error_count: number;
            /**
             * Input
             * @description Input provided to the agent for this run.
             */
            input: string | null;
            /**
             * Output
             * @description Output produced by the agent run.
             */
            output: string | null;
            /**
             * Priority
             * @description Indicates if the run was treated as a priority execution.
             */
            priority: boolean;
            /**
             * Run Id
             * @description Unique identifier for the agent run.
             */
            run_id: string;
            /** @description Current status of the agent run. */
            status: components["schemas"]["PendingProcessingCompletedFailedStatus"];
        };
        /** AgentRunStreamRequest */
        AgentRunStreamRequest: {
            /**
             * Input
             * @description Input to provide to the agent upon running for agents with dynamic triggers.
             */
            input: string | null;
            /**
             * Metadata
             * @description Metadata to make available for string substitution expressions in agent tasks.
             */
            metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
        };
        /** Body_upload_file_to_source_api_sources__source_connection_id__upload_post */
        Body_upload_file_to_source_api_sources__source_connection_id__upload_post: {
            /**
             * File
             * Format: binary
             * @description File to upload
             */
            file: string;
            /**
             * Title
             * @description Optional title for the content
             */
            title?: string;
        };
        /**
         * ContentEmbeddingResponse
         * @description Response model for content embedding.
         */
        ContentEmbeddingResponse: {
            /** Batch Duration */
            batch_duration: number;
            /** Batch Size */
            batch_size: number;
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Text End */
            text_end: number;
            /** Text Start */
            text_start: number;
            /** Vector */
            vector: number[];
        };
        /**
         * FileUploadResponse
         * @description Response model for file upload
         */
        FileUploadResponse: {
            /**
             * Content Version Id
             * @description ID of the created content version
             */
            content_version_id: string | null;
            /**
             * Filename
             * @description Original filename
             */
            filename: string;
            /**
             * Source Connection Content Version Id
             * @description ID of the duplicate source connection content version
             */
            source_connection_content_version_id: string | null;
            /**
             * Status
             * @description Processing status
             */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /**
         * PaginationResponse
         * @description Pagination information.
         */
        PaginationResponse: {
            /** Has Next */
            has_next: boolean;
            /** Has Prev */
            has_prev: boolean;
            /** Limit */
            limit: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
            /** Total */
            total: number;
        };
        /**
         * PendingProcessingCompletedFailedStatus
         * @enum {string}
         */
        PendingProcessingCompletedFailedStatus: "pending" | "processing" | "completed" | "failed";
        /**
         * SourceResponse
         * @description Response model for source data.
         */
        SourceResponse: {
            /**
             * Account Id
             * Format: uuid
             * @description Account ID associated with the source.
             */
            account_id: string;
            /**
             * Avg Episodes Per Month
             * @description Average number of episodes per month.
             */
            avg_episodes_per_month?: number | null;
            /**
             * Avg Words Per Episode
             * @description Average number of words per episode.
             */
            avg_words_per_episode?: number | null;
            /**
             * Chunk Language
             * @description Language used for chunking content.
             */
            chunk_language?: string | null;
            /**
             * Chunk Overlap
             * @description Chunk overlap for content processing.
             */
            chunk_overlap?: number | null;
            /**
             * Chunk Regex Separators
             * @description Indicates if chunk separators are regex patterns.
             */
            chunk_regex_separators?: boolean | null;
            /**
             * Chunk Separators
             * @description Chunk separators used for content processing.
             */
            chunk_separators?: string | null;
            /**
             * Chunk Size
             * @description Chunk size for content processing.
             */
            chunk_size?: number | null;
            /**
             * Content Count
             * @description Number of content items associated with the source connection.
             * @default 0
             */
            content_count: number;
            /**
             * Content Filter
             * @description Content filter for the source connection.
             */
            content_filter: string;
            /**
             * Created At
             * @description Timestamp when the source connection was created.
             */
            created_at: string;
            /**
             * Dimensions
             * @description Dimensions of the embedding model.
             */
            dimensions?: number | null;
            /**
             * Embedding Model
             * @description Embedding model used for the source connection.
             */
            embedding_model?: string | null;
            /**
             * Embedding Model Type
             * @description Type of the embedding model.
             */
            embedding_model_type?: string | null;
            /**
             * Has Historical Data
             * @description Indicates if the source connection has historical data.
             * @default false
             */
            has_historical_data: boolean;
            /**
             * Id
             * @description Unique identifier for the source connection.
             */
            id: string;
            /**
             * Name
             * @description Name of the source connection.
             */
            name: string;
            /**
             * Next Poll At
             * @description Timestamp for the next scheduled poll.
             */
            next_poll_at: string | null;
            /**
             * Polling
             * @description Polling configuration for the source connection.
             */
            polling: string | null;
            /**
             * Polling Action
             * @description Polling action for the source connection.
             */
            polling_action: string | null;
            /**
             * Polling Max Items
             * @description Maximum items to poll for the source connection.
             */
            polling_max_items: number | null;
            /**
             * Pulled At
             * @description Timestamp when content was last pulled.
             */
            pulled_at: string | null;
            /**
             * Readonly
             * @description Indicates if the source connection is read-only.
             * @default false
             */
            readonly: boolean;
            /**
             * Retention
             * @description Retention period for the source connection.
             */
            retention: number | null;
            /**
             * Source Type
             * @description Type of the source connection.
             */
            source_type: string;
            /**
             * Updated At
             * @description Timestamp when the source connection was last updated.
             */
            updated_at: string;
            /**
             * Url
             * @description URL of the source connection.
             */
            url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** AgentRunListResponse */
        routers__api__agents__AgentRunListResponse: {
            /**
             * Data
             * @description List of agent runs.
             */
            data: components["schemas"]["AgentRunResponse"][];
            pagination: components["schemas"]["PaginationResponse"];
        };
        /**
         * ContentDetailResponse
         * @description Response model for content detail.
         */
        routers__api__contents__ContentDetailResponse: {
            /**
             * Content Duration
             * @description Duration of the content in seconds.
             */
            content_duration: number | null;
            /**
             * Content Duration Display
             * @description Display string for content duration.
             */
            content_duration_display: string | null;
            /**
             * Content Status
             * @description Status of the content.
             */
            content_status: string;
            /**
             * Content Type
             * @description Type of the content.
             */
            content_type: string;
            /**
             * Content Type Display
             * @description Display name of the content type.
             */
            content_type_display: string;
            /**
             * Content Url
             * @description URL of the content.
             */
            content_url: string;
            /**
             * Content Word Count
             * @description Word count of the content.
             */
            content_word_count: number | null;
            /**
             * Description
             * @description Description of the content.
             */
            description: string | null;
            /**
             * Error
             * @description Error message, if any.
             */
            error: string | null;
            /**
             * Id
             * @description Unique identifier for the content version.
             */
            id: string;
            /**
             * Metadata
             * @description Metadata associated with the content.
             */
            metadata: {
                [key: string]: string;
            }[] | null;
            /**
             * Published At
             * @description Timestamp when the content was published.
             */
            published_at: string | null;
            /**
             * Pulled At
             * @description Timestamp when the content was pulled.
             */
            pulled_at: string;
            /**
             * Source Connection Content Version Id
             * @description ID of the source connection content version.
             */
            source_connection_content_version_id: string;
            /**
             * Source Connection Id
             * @description ID of the source connection.
             */
            source_connection_id: string;
            /**
             * Source Name
             * @description Name of the source.
             */
            source_name: string;
            /**
             * Source Type
             * @description Type of the source.
             */
            source_type: string;
            /**
             * Text Content
             * @description Text content.
             */
            text_content: string | null;
            /**
             * Text Content End
             * @description End position of the text content.
             */
            text_content_end: number;
            /**
             * Text Content Start
             * @description Start position of the text content.
             */
            text_content_start: number;
            /**
             * Text Content Total Length
             * @description Total length of the text content.
             */
            text_content_total_length: number;
            /**
             * Title
             * @description Title of the content.
             */
            title: string | null;
        };
        /**
         * ContentEmbeddingsListResponse
         * @description Response model for paginated content embeddings.
         */
        routers__api__contents__ContentEmbeddingsListResponse: {
            /** Data */
            data: components["schemas"]["ContentEmbeddingResponse"][];
            pagination: components["schemas"]["PaginationResponse"];
        };
        /**
         * SourceListResponse
         * @description Response model for paginated source list
         */
        routers__api__sources__SourceListResponse: {
            /** Data */
            data: components["schemas"]["SourceResponse"][];
            pagination: components["schemas"]["PaginationResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agent_runs_api_agents__agent_id__runs_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
            };
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["routers__api__agents__AgentRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_agent_api_agents__agent_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_streaming_agent_api_agents__agent_id__runs_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunStreamRequest"];
            };
        };
        responses: {
            /**
             * @description Streams agent run events via Server-Sent Events (SSE); run is always created as priority.
             *
             *     SSE events:
             *     - `event: init` — `data` is an `AgentRunResponse` snapshot (includes `run_id`).
             *     - `event: done` — `data` is the final `AgentRunResponse` snapshot (includes `output`, `credits`, etc).
             *     - Other events (e.g. `status`, step events) are forwarded from the run event stream.
             *     - On `timeout` / `error`, the payload includes `run_id` so clients can fetch status via `GET /api/agents/{agent_id}/runs/{run_id}`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    /**
                     * @example : keepalive
                     *
                     *     event: init
                     *     data: {"run_id":"...","status":"pending","error_count":0,"credits":0.0,"priority":true,"input":"...","output":null,"attempts":[]}
                     *
                     *     event: done
                     *     data: {"run_id":"...","status":"completed","error_count":0,"credits":0.0,"priority":true,"input":"...","output":"...","attempts":[]}
                     */
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_run_api_agents__agent_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_run_api_agents__agent_id__runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_detail_api_contents__source_connection_content_version__get: {
        parameters: {
            query?: {
                start?: number;
                end?: number;
            };
            header?: never;
            path: {
                source_connection_content_version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["routers__api__contents__ContentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_content_api_contents__source_connection_content_version__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_connection_content_version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_content_embeddings_api_contents__source_connection_content_version__embeddings_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                source_connection_content_version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["routers__api__contents__ContentEmbeddingsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_sources__get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
                /** @description Sort field */
                sort?: string;
                /** @description Sort order */
                order?: string;
                /** @description List sources for the given account. Defaults to the api key's account. */
                account_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["routers__api__sources__SourceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_to_source_api_sources__source_connection_id__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_to_source_api_sources__source_connection_id__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
